### ISSUE TITLE
simulator error

### ISSUE THREAD

**Issue by BatmanPDX** [austinyearlykim/wolf#57]
I get this error when I try to run the simulator:

> wolf@3.5.0 simulator C:\wolf
> mocha simulator.js --exit

module.js:549
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wolf\simulator.js:15:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\Triangle\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Triangle\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\Triangle\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\Triangle\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wolf@3.5.0 simulator: `mocha simulator.js --exit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wolf@3.5.0 simulator script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Triangle\AppData\Roaming\npm-cache\_logs\2018-05-29T01_39_41_632Z-debug.log

**Comment by BatmanPDX** [comment]
damnit, haha I always forget to install the damn dependents.

**Comment by austinyearlykim** [comment]
haha! nice.
