### ISSUE TITLE
buy limit feature

### ISSUE THREAD

**Issue by Orbitalz-eth** [austinyearlykim/wolf#64]
I would gladly pay $20 for a buy-limit feature.  A simple "buy at current bid price" and "buy at percentage below bid price" is all I'm looking for.

**Comment by austinyearlykim** [comment]
agreed.  I'll prioritize this feature for this weekend as it seems one of the easiest to get time to work on atm as well.  Don't worry about the $20.  Stay tuned @BatmanPDX

**Comment by Orbitalz-eth** [comment]
Just to add a lil bit of insurance to the feature:
Buy_At_Current_BidPrice = True
BuyLimit_WaitTime = 30.00     (30 mins)

The wait time feature would be very beneficial for moments when the price dips below your current buylimit. There's no telling how many minutes or even hours you might be waiting before it goes back up to your buylimit.
If the WaitTime is triggered, the bought will cancel the current buylimit and create a new one.

**Comment by austinyearlykim** [comment]
hey @BatmanPDX,

I got a chance to get the feature up on a branch.

Read the new README.md on how the new feature works and let me know what you think.  Going to merge this in to master either tomorrow or early next week if testing goes well!

`git fetch --all`
`git checkout buy-limit-feature`
`npm test`
`npm start`

**Comment by Orbitalz-eth** [comment]
awesome, I'll check it out

**Comment by Orbitalz-eth** [comment]
Sorry, haven't had time to check it out yet. been doing some market research

**Comment by Orbitalz-eth** [comment]
Just tested the feature! it works great!
 took me a few tries to figure out what the percent was for 1 sat below the asking price was. 
Great job!

**Comment by Orbitalz-eth** [comment]
damn, spoke too soon. I got this message when the time-reset was triggered: my time-reset is set to 0.30 (30 seconds)

 Buy limit reset time reached.  Cancelling current order(s)
- Queue: 0 Watchlist: 1(node:6492) UnhandledPromiseRejectionWarning: ReferenceError: queue is not defined
    at Wolf.consume (C:\wolf\modules\Wolf.js:95:37)
    at tickerConfig.callbacks (C:\wolf\modules\Wolf.js:49:28)
    at callbacks.forEach (C:\wolf\modules\Ticker.js:45:52)
    at Array.forEach (<anonymous>)
    at binance.ws.partialDepth (C:\wolf\modules\Ticker.js:45:36)
    at WebSocket.<anonymous> (C:\wolf\node_modules\binance-api-node\dist\websocket.js:76:7)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (C:\wolf\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\wolf\node_modules\ws\lib\Receiver.js:389:14)
(node:6492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\ Queue: 0 Watchlist: 1

**Comment by BatmanPDX** [comment]
It seems to happen right when the buy-limit goes through.

**Comment by Orbitalz-eth** [comment]
when the buy-limit goes through but the sell doesn't go through in a certain amount of time; it also shows that bug message.

**Comment by austinyearlykim** [comment]
I believe I fixed it: https://github.com/austinyearlykim/wolf/issues/66

**Comment by austinyearlykim** [comment]
In lieu of recent discovery of a potential race condition I think it's best that I hold this feature off until the 4.0.0 release.  I will be closing this branch for now.  Please use ```master``` branch for all near-future bot activity!

Thanks all for being proactive.

**Comment by danielro7587** [comment]
hi
is there any way for set buy limit order now?

**Comment by austinyearlykim** [comment]
Hi @danielro7587,

I'm afraid my off-time has been spent on a private stock market solution right now and haven't gotten the time to implement buy-limits.
